### ISSUE TITLE
MacOS M1: symbol not found in flat namespace '_notmuch_config_list_destroy'

### ISSUE THREAD

**Issue by sstepashka** [weilbith/notmuch2-python-bindings#4]
Hi,

Could you help me to make the code work on MacOS?

I have this error when trying to import notmuch2:
```
symbol not found in flat namespace '_notmuch_config_list_destroy'
```

I do understand that it's caused by version mismatching of compiled modules, but I would appreciate help in finding a solution. `notmuch` is installed via homebrew. This binding is installed by `lieer` as dependency. I tried:
```
cat ~/dotfiles/install-lieer.sh
#!/usr/bin/env sh
# -*- coding: utf-8 -*-

set -e

PYTHON=`which python3`

arch -arm64 $PYTHON -m virtualenv ~/lieer-venv1

. ~/lieer-venv1/bin/activate

arch -arm64 python -m pip install --upgrade pip

pushd ~/lieer-venv1

git clone git@github.com:gauteh/lieer.git

pushd lieer

LDFLAGS=-L$(brew --prefix libffi)/lib CFLAGS=-I$(brew --prefix libffi)/include arch -arm64 pip install cffi --no-binary :all:

#arch -arch arm64 python -m pip install cffi

CFLAGS="-I`brew --prefix`/include" \
  LDFLAGS="-L`brew --prefix`/lib" \
  arch -arch arm64 python -m pip install notmuch2 --no-binary :all:

arch -arch arm64 python -m pip install --use-pep517 .
  #DYLD_LIBRARY_PATH="`brew --prefix`/lib" \

popd
popd
```

and it didn't work. The brew versions seems like have the expected architecture...

**Comment by lucc** [comment]
The notmuch [formula in homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/notmuch.rb) contains the matching python bindings, why not just use those?

**Comment by sstepashka** [comment]
@lucc it is quite reasonable question... because lieer somehow can't import them? Maybe I did something wrong and used system python instead of the one comes with brew.


BTW, that was exactly the problem with `symbol not found in flat namespace`. When I was installing the lib, cffi was using brew python, but when I run it (through virtualenv) it uses system python. So, python versions do not match and the symbols are not available. 

I think I will give it a try next time! Thank you for the suggestion! I didn't know notmuch2 comes with its own python bindings...
